default:
  image: node:14.16.0
  cache:
    paths:
      - node_modules
  timeout: 2h

stages: 
  - install
  - build

job_install:
  stage: install
  script: npm install
  only:
    - tags

job_build:
  stage: build
  before_script:
    - env
    - mv /etc/apt/sources.list /etc/apt/sources.list.bak
    - curl -s https://gitlab.internal.live-helps.com/ltd-public/build-scripts/-/raw/master/NODE/debian10_source_list -o /tmp/sources.list
    - cp /tmp/sources.list /etc/apt/sources.list
    - apt-get update
    - apt-get install zip
  script:  
    - sh ./travis/pack.sh
    - sh ./travis/upload.sh
  only:
    - tags
